### ISSUE TITLE
This definitely works on Android 12 (For the most part)

### ISSUE THREAD

**Issue by Thisisauser6443** [logmd/N3O-No-Nonsense-Notch-Overlay#4]
So, after updating to Android 12 this module did seem to work perfectly fine, with all 3 of the pre-made layouts working as intended. However, I ran into an issue while I was re-installing the module, specifically saying that there is the chance that there is a ROM incompatibility with the stock Pixel 4a 5G ROM I had, but it did work like it had on A11, as I had previously mentioned

So, I'm just asking really, if you're planning to get this up to Android 12 as well (because it seems that the intended target was A11)?
Grazie :)

**Comment by logmd** [comment]
have not got round to it yet, personal life been extremely busy. i reckon it shouldnt be too difficult yet :) also i dont have android 12 yet... oneplus taking their sweet time for stable!

**Comment by Thisisauser6443** [comment]
Oh, rip, that's fair. Meanwhile, I accidentally came across a workaround for it - Installing it through Magisk gives the ROM incompatibility error, but installing it through Fox's MMM (which honestly just looks like the same process) is perfectly fine for A12!

How that works just puzzles me xD

**Comment by Thisisauser6443** [comment]
Completely forgot to tell you if _1.4Q2H.01-29-40_ was working, lmao, but it seems to be working nicely for me :)

Edit: Well... Almost nicely. There's this weird behaviour where the height of the status bar changes after returning from horizontal orientation (This occurred after heading over to the June 2022 patch, where the default position with N3O enabled was moved marginally lower compared to the May 2022 patch). Easy way to revert that is just a restart of the System UI
